---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- DateTime: 2020/2/8 17:21
--- 一个按照规范实现的逻辑模块
--- 1. 不允许包内 local 变量
--- 2. 不允许使用闭包
--- 3. 只更新包内函数成员

local M = {}

M.foo = function()
    print "Hello from my mod foo."
end

M.bar = function()
    print "Hello from my mod bar."
end

return M