---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- DateTime: 2020/2/8 17:27
--- 将要被更新替换上去的新逻辑

local mymod_new = {}

mymod_new.foo = function()
    print("WORLD from mymod_new foo.")
end

mymod_new.bar = function()
    print("WORLD from mymod_new bar.")
end

mymod_new.new_bar = function()
    print("new bar function from mymod_new.")
end

--- 下面是一些初始化代码，初始化过程只允许使用 reload 沙箱中的安全函数
print("new mod loading...") -- this line will be running succeed.
--debug.getregistry() -- this line is not safe, so reload function will reject it.

return mymod_new